version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crm
    ports:
      - "5432:5432"

  redis:
    image: redis:7

  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
    env_file:
      - ./backend/.env.example
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: ./backend
    command: celery -A app.celery.tasks worker --loglevel=info
    depends_on:
      - backend
      - redis
